### ISSUE TITLE
変数が文字列で渡ってきているのに型確認をしている箇所を修正する必要がある

### ISSUE THREAD

**Issue by mako5656** [quartetcom/openapi-generator-php-templates#2]
## 概要

メソッドの引数が文字列で渡ってきているのに対し内部で型確認をしている箇所があるので修正する必要がある。
ベストは`::class`(型確認)を優先して修正する必要がある

## 今確認できている該当箇所

- https://github.com/quartetcom/openapi-generator-php-templates/blob/a72d25a85581e7faf2dbd47f3516ea6dab230153/templates/ObjectSerializer.mustache#L429
- https://github.com/quartetcom/openapi-generator-php-templates/blob/a72d25a85581e7faf2dbd47f3516ea6dab230153/templates/ObjectSerializer.mustache#L450
- https://github.com/quartetcom/openapi-generator-php-templates/blob/a72d25a85581e7faf2dbd47f3516ea6dab230153/templates/ObjectSerializer.mustache#L215C30-L215C38

## このissueについての発見のやりとり

https://github.com/quartetcom/freee-invoice-sdk/issues/12

**Comment by siketyan** [comment]
Fixed in f4c8f171
